/**
 * Database Setup Script
 *
 * Complete database setup for ephemeral sandboxes:
 * 1. Provision Wrangler secrets (.dev.vars file)
 * 2. Wait for database to be ready
 * 3. Run migrations
 * 4. Run seed
 *
 * Usage:
 *   bun run db:setup
 *
 * Environment:
 *   DATABASE_URL - PostgreSQL connection string (optional, has default)
 *   BETTER_AUTH_SECRET - Auth secret (auto-generated if missing)
 */

import postgres from "postgres";
import { execSync } from "child_process";
import { randomBytes } from "crypto";
import { existsSync, readFileSync, writeFileSync, appendFileSync } from "fs";
import { resolve } from "path";

// Wrangler uses .dev.vars for local secrets (not .env)
const ENV_FILE = resolve(import.meta.dirname, "../.dev.vars");
const ENV_EXAMPLE_FILE = resolve(import.meta.dirname, "../.dev.vars.example");

// Default values for ephemeral sandboxes
const DEFAULTS = {
  DATABASE_URL: "postgresql://lumea:lumea@localhost:5432/lumea",
  NODE_ENV: "development",
  CORS_ORIGINS: "http://localhost:3000,http://localhost:5173",
  BETTER_AUTH_URL: "http://localhost:3001",
  LOG_LEVEL: "info",
};

/**
 * Generate a cryptographically secure secret
 */
function generateSecret(bytes = 32): string {
  return randomBytes(bytes).toString("base64");
}

/**
 * Parse .env file content into key-value pairs
 */
function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      // Remove surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      env[key] = value;
    }
  }
  return env;
}

/**
 * Provision environment variables
 * - Creates .env from .env.example if missing
 * - Generates BETTER_AUTH_SECRET if not set
 * - Sets defaults for missing required variables
 */
function provisionEnv(): void {
  console.log("🔧 Provisioning environment variables...\n");

  let envContent = "";
  let existingEnv: Record<string, string> = {};

  // Load existing .dev.vars or create from example
  if (existsSync(ENV_FILE)) {
    envContent = readFileSync(ENV_FILE, "utf-8");
    existingEnv = parseEnvFile(envContent);
    console.log("   Found existing .dev.vars file");
  } else if (existsSync(ENV_EXAMPLE_FILE)) {
    envContent = readFileSync(ENV_EXAMPLE_FILE, "utf-8");
    existingEnv = parseEnvFile(envContent);
    writeFileSync(ENV_FILE, envContent);
    console.log("   Created .dev.vars from .dev.vars.example");
  } else {
    console.log("   No .dev.vars found, creating new .dev.vars");
  }

  const additions: string[] = [];

  // Check and set DATABASE_URL
  if (!existingEnv.DATABASE_URL && !process.env.DATABASE_URL) {
    additions.push(`DATABASE_URL="${DEFAULTS.DATABASE_URL}"`);
    process.env.DATABASE_URL = DEFAULTS.DATABASE_URL;
    console.log(`   ✓ Set DATABASE_URL (default: ${DEFAULTS.DATABASE_URL})`);
  } else {
    process.env.DATABASE_URL = existingEnv.DATABASE_URL || process.env.DATABASE_URL;
    console.log("   ✓ DATABASE_URL already set");
  }

  // Generate BETTER_AUTH_SECRET if missing
  if (!existingEnv.BETTER_AUTH_SECRET ||
      existingEnv.BETTER_AUTH_SECRET.includes("generate-with")) {
    const secret = generateSecret(32);
    additions.push(`BETTER_AUTH_SECRET="${secret}"`);
    process.env.BETTER_AUTH_SECRET = secret;
    console.log("   ✓ Generated BETTER_AUTH_SECRET");
  } else {
    console.log("   ✓ BETTER_AUTH_SECRET already set");
  }

  // Set other defaults
  for (const [key, defaultValue] of Object.entries(DEFAULTS)) {
    if (key === "DATABASE_URL") continue; // Already handled
    if (!existingEnv[key] && !process.env[key]) {
      additions.push(`${key}="${defaultValue}"`);
      process.env[key] = defaultValue;
      console.log(`   ✓ Set ${key} (default)`);
    }
  }

  // Append new variables to .env
  if (additions.length > 0) {
    const separator = envContent.endsWith("\n") || envContent === "" ? "" : "\n";
    const newContent = `${separator}\n# Auto-generated by setup script\n${additions.join("\n")}\n`;
    appendFileSync(ENV_FILE, newContent);
    console.log(`\n   📝 Added ${additions.length} variable(s) to .dev.vars`);
  }

  console.log("");
}

// Run provisioning first
provisionEnv();

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("DATABASE_URL environment variable is required");
  process.exit(1);
}

async function waitForDatabase(maxAttempts = 30, delayMs = 1000): Promise<void> {
  console.log("⏳ Waiting for database to be ready...");

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const client = postgres(connectionString!, { max: 1 });
      await client`SELECT 1`;
      await client.end();
      console.log("✅ Database is ready!");
      return;
    } catch (error) {
      if (attempt === maxAttempts) {
        console.error(`❌ Database not ready after ${maxAttempts} attempts`);
        process.exit(1);
      }
      console.log(`   Attempt ${attempt}/${maxAttempts} - waiting ${delayMs}ms...`);
      await new Promise((resolve) => setTimeout(resolve, delayMs));
    }
  }
}

async function setup() {
  console.log("🚀 Starting database setup...\n");

  // 2. Wait for database (step 1 was env provisioning above)
  await waitForDatabase();

  // Pass environment to child processes (drizzle-kit needs DATABASE_URL)
  const childEnv = { ...process.env };

  // 3. Generate Better Auth schema
  console.log("\n🔐 Generating Better Auth schema...");
  try {
    execSync("bun run db:auth:generate", { stdio: "inherit", env: childEnv });
    console.log("✅ Auth schema generated!");
  } catch (error) {
    console.error("❌ Better Auth schema generation failed:", error);
    process.exit(1);
  }

  // 4. Run Drizzle push (creates all tables: auth + app)
  console.log("\n📦 Creating database tables...");
  try {
    execSync("bun run db:push", { stdio: "inherit", env: childEnv });
    console.log("✅ Database tables created!");
  } catch (error) {
    console.error("❌ Database setup failed:", error);
    process.exit(1);
  }

  // 5. Run seed
  console.log("\n🌱 Running seed...");
  try {
    execSync("bun run db:seed", { stdio: "inherit", env: childEnv });
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }

  console.log("\n🎉 Database setup complete!");
}

setup();
